
# icons chart : http://fa2png.io/r/ionicons/
# theme references: https://github.com/themefisher/navigator-hugo
#                   https://themes.gohugo.io/navigator-hugo/
baseURL: 'https://beta.jdlabs.co/'
languageCode: en-ca
title: JD Labs Inc.
theme: navigator-hugo
copyright: "Copyright Â© {year} JD Labs Technologies Inc. All rights reserved."
enableRobotsTXT: true
# Menu and sections
menu:
  nav:
    - name: About
      url: /about
      weight: 2
    - name: Service
      url: /service
      weight: 3
    # - name: Portfolio
    #   url: /portfolio
    #   weight: 4
    # - name: Blog
    #   url: /blog
    #   weight: 5
    - name: Contact
      url: /contact
      weight: 6
  service:
    - name: Application Development
      url: /service
      weight: 1
    - name: Cloud & Hosting
      url: /service
      weight: 2
    - name: DevOps
      url: /service
      weight: 3
  company:
    - name: About
      url: /about
      weight: 1
    - name: Contact
      url: /contact
      weight: 2
    - name: Careers
      url: /careers
      weight: 3
params:
  home: Home
  logo: images/logo.png
  dateFormat: 1 August 2018
  footerDescription: >-
    At JD Labs we are part of your development team, we are your extension team and we are always ready to code.
  hero:
    enable: true
    heading: We are your extension development team
    description: >-
      We created JD Labs because we love building tomorrow's technologies. We have been around for many years helping
      companies build and host many innovative applications. Our group of experts offers our clients an entire team 
      that can expand your existing development team or take on the extra development projects you do not have time to
      realise. We can create proof of concept, write new applications, host and operate your application while you 
      concentrate on your true business.
    button: true
    btnText: Contact Us
    btnURL: '/contact'
    videoThumb: /images/splash/5.png
    # videoURL: 'https://www.youtube.com/embed/g3-VxLQO7do'
  aboutSm:
    labelFooter: ABOUT
    enable: true
    title: We have explored the application development landscape with passion for a long time
    description: >-
      Our team is made of true experts that have more then ten years of experience in their respective fields.
      Our team code, host and maintain software every day. We are used to test new technologies and try them to
      better assist our clients into choosing the right technology for their needs.
  company:
    labelFooter: COMPANY
  service:
    labelFooter: OUR SERVICES
  blog:
    enable: false
    topTitle: OUR UNTOLD STORY
    title: Blog.
    subtitle: >-
      Let's share a bit of our experience
  cta:
    enable: true
    bg: images/call-to-action/call-to-action-bg-2.jpg
    title: Let's Create Something Together
    subtitle: >-
      Not sure where to start with your new application development or having to much projects on your plate already?
      <br />
      Our team is ready for your project! From architecture, to realisation and operations, we can help you realise
      your next innovative project.
    btnText: Contact Us
    btnURL: '/contact'
  contact:
    labelFooter: FOLLOW US
    enable: true
    topTitle: DROP US A NOTE
    title: Contact Us.
    subtitle: >-
      Questions about how we can help or if you want to discuss about a new technology you want us to help you with.
      Drop us a note or call us. 
    address: '3 Place Ville Marie #400, Montreal, QC H3B 2E3'
    addressLabel: Our Location
    phone: (514) 575-2497
    phoneLabel: Call Us
    # fax: +61 3827 3590
    # facebook: 'https://www.facebook.com/'
    socialLabel: We are social
    twitter: 'https://twitter.com/JDLabsMTL/'
    linkedin: 'https://www.linkedin.com/jdlabsmtl/'
    # dribbble: 'https://dribbble.com/'
    # instagram: 'https://www.instagram.com/'
    btnText: Submit
    mapLatitude: '45.501872'
    mapLongitude: '-73.568811'
    mapMarker: images/marker.png
    namePlaceholder: Your Name
    messagePlaceholder: Message
    subjectPlaceholder: Subject
    emailPlaceholder: Your Email
