# icons chart : http://fa2png.io/r/ionicons/
# theme references: https://github.com/themefisher/navigator-hugo
#                   https://themes.gohugo.io/navigator-hugo/
baseURL: "https://beta.jdlabs.co/en/"
languageCode: en-ca
title: JD Labs Inc.
theme: navigator-new
copyright: "Copyright Â© {year} JD Labs Technologies Inc. All rights reserved."
enableRobotsTXT: true
# Menu and sections
menu:
  nav:
    - name: About
      url: /about
      weight: 1
    - name: Service
      url: /service
      weight: 2
    # - name: Portfolio
    #   url: /portfolio
    #   weight: 4
    # - name: Blog
    #   url: /blog
    #   weight: 5
    - name: Contact
      url: /contact
      weight: 3
  service:
    - name: Application Development
      url: /service
      weight: 1
    - name: Cloud & Hosting
      url: /service
      weight: 2
    - name: DevOps
      url: /service
      weight: 3
  company:
    - name: About
      url: /about
      weight: 1
    - name: Contact
      url: /contact
      weight: 2
    - name: Careers
      url: /careers
      weight: 3
    - name: Our Services
      url: /service
      weight: 4
    - name: French
      url: /
      weight: 5
params:
  author: JD Labs Technologies Inc.
  description: Welcome to JD Labs Technologies Inc.
  googleTagManager: UA-118656387-1
  home: Home
  logo: images/logo.svg
  logo2: images/logo2.svg
  dateFormat: 1 August 2018
  otherLanguage:
    label: fr
    url: /
  footerDescription: >-
    At JD Labs we are part of your development team. Consider us your extension team : always ready to code.
  hero:
    enable: true
    heading: Empowering you today through the technologies of tomorrow.
    description: >-

    button: true
    
    btnText: Contact Us
    btnURL: "/en/contact"
    logo: images/logowhite.svg
    videoThumb: images/splash/5.png
    # videoURL: 'https://www.youtube.com/embed/g3-VxLQO7do'
  aboutSm:
    labelFooter: ABOUT
    enable: true
    title: We created JD Labs, because we are extremely experienced in building the technologies of tomorrow.
    description: >-
      We have been consultants for many years, helping companies build and host diverse technologies. Our group of experts 
      can offer you a team who can expand your existing development team or take on additional development projects that you don't have time for. 
      We can create a proof of concept, write new apps, host and operate your app, while you focus on your business. Our team codes, hosts and maintains software every day. 
    bg: images/workingpeople.jpg
    title2: We constantly experiment with and test new technologies in order to offer to our clients the best technology suited for their present and growing needs.
  company:
    labelFooter: COMPANY
  service:
    labelFooter: OUR SERVICES
  blog:
    enable: false
    topTitle: OUR UNTOLD STORY
    title: Blog.
    subtitle: >-
      Let's share a bit of our experience
  cta:
    enable: true
    bg: images/call-to-action/call-to-action-bg-2.jpg
    title: Let's Create Something Together
    subtitle: >-
      Not sure where or how to start your new application development?
      <br />
      Our team is ready for your project. From architecture, to realisation and operations, we can help you launch
      your next innovative project.
    btnText: Contact Us
    btnURL: "/en/contact"
  errorPage:
    topTitle: 404
    title: Page not found
    btnText: Welcome
    btnURL: "/fr/"
    description: Sorry, but the page you were trying to view does not exist.
  contact:
    labelFooter: FOLLOW US
    enable: true
    topTitle: DROP US A NOTE
    mapImage: images/contact/map.png
    title: Contact Us.
    subtitle: >-
      Call us for any questions on new technologies or how we can best serve your needs.
      Drop us a note or call.
    address: "7027 rue de Monaco, Saint-Hubert, Quebec, J3Z 0C7"
    addressLabel: Our Location
    phone: (514) 575-2497
    phoneLabel: Call Us
    # fax: +61 3827 3590
    # facebook: 'https://www.facebook.com/'
    socialLabel: We are social
    twitter: "https://twitter.com/JDLabsMTL/"
    linkedin: "https://www.linkedin.com/company/jdlabs/"
    # dribbble: 'https://dribbble.com/'
    # instagram: 'https://www.instagram.com/'
    btnText: Submit
    mapLatitude: 45.501872
    mapLongitude: -73.568811
    mapMarker: images/marker.png
    namePlaceholder: Your Name
    messagePlaceholder: Message
    subjectPlaceholder: Subject
    emailPlaceholder: Your Email
    formActionURL: /api/index.php
    formActionSuccess: Thank you. We will get back to you shortly.
    formActionError: We are sorry an error happened. Please call us.
