
# icons chart : http://fa2png.io/r/ionicons/
# theme references: https://github.com/themefisher/navigator-hugo
#                   https://themes.gohugo.io/navigator-hugo/
baseURL: 'https://beta.jdlabs.co/'
languageCode: fr-ca
title: JD Labs Inc.
theme: navigator-hugo
copyright: "© {year} JD Labs Technologies Inc. Tous droits réservés."
enableRobotsTXT: true
# Menu and sections
menu:
  nav:
    - name: À Propos
      url: /about
      weight: 1
    - name: Services
      url: /service
      weight: 2
    # - name: Portfolio
    #   url: /portfolio
    #   weight: 4
    # - name: Blog
    #   url: /blog
    #   weight: 5
    - name: Contactez-Nous
      url: /contact
      weight: 3
  service:
    - name: Développement Applicatif
      url: /service
      weight: 1
    - name: Cloud & Hébergement
      url: /service
      weight: 2
    - name: DevOps
      url: /service
      weight: 3
  company:
    - name: À Propos
      url: /about
      weight: 1
    - name: Contactez-Nous
      url: /contact
      weight: 2
    - name: Carrières
      url: /careers
      weight: 3
    - name: Nos Services
      url: /service
      weight: 4
    - name: English
      url: /en/
      weight: 5
params:
  author: JD Labs Technologies Inc.
  description: Bienvenue chez JD Labs Technologies Inc.
  googleTagManager: UA-118656387-1
  home: Accueil
  logo: images/logo.png
  dateFormat: 1 August 2018
  otherLanguage:
    label: en
    url: /en
  footerDescription: >-
    Chez JD Labs, nous faisons parti de votre équipe de développement. Nous sommes votre équipe d'extension.
  hero:
    enable: true
    heading: Nous sommes votre équipe de développement d'extension
    description: >-
      Nous avons créé JD Labs, parce que nous aimons construire les technologies de demain. Nous avons été consultant pendant de nombreuses années tout en aidant
      les entreprises à construire et héberger de nombreuses technologies. Notre groupe d'experts offre à nos clients une équipe entière,
      qui peut agrandir votre équipe de développement existante ou prendre en charge les projets de développement supplémentaires que vous n'avez pas le temps de réaliser.
      Nous pouvons créer une preuve de concept, écrire de nouvelles applications, héberger et exploiter votre application, pendant que vous vous concentrez sur vos affaires.
    button: true
    btnText: Contactez-Nous
    btnURL: '/contact'
    videoThumb: /images/splash/5.png
    # videoURL: 'https://www.youtube.com/embed/g3-VxLQO7do'
  aboutSm:
    labelFooter: ACCUEIL
    enable: true
    title: Nous avons exploré avec passion le paysage du développement d'applications depuis longtemps
    description: >-
      Notre équipe est composée de véritables experts, qui ont plus de dix ans d'expérience dans leurs domaines respectifs.
      Notre équipe code, héberge et maintient des logiciels tous les jours. Nous avons l'habitude de tester de nouvelles technologies et de les essayer pour
      mieux aider nos clients à choisir la technologie adaptée à leurs besoins.
  company:
    labelFooter: COMPAGNIE
  service:
    labelFooter: NOS SERVICES
  blog:
    enable: false
    topTitle: Notre histoire
    title: Blog.
    subtitle: >-
      Let's share a bit of our experience
  cta:
    enable: true
    bg: images/call-to-action/call-to-action-bg-2.jpg
    title: Créons quelque chose ensemble!
    subtitle: >-
      Vous ne savez pas par où commencer avec le développement de votre nouvelle application ou avez déjà beaucoup de projets dans votre assiette?
      <br />
      Notre équipe est prête pour votre projet! De l'architecture, à la réalisation et aux opérations, nous pouvons vous aider à réaliser votre prochain projet technologique.
    btnText: Contactez-Nous
    btnURL: '/contact'
  errorPage:
    topTitle: 404
    title: Page Non Trouvée  
    btnText: Accueil
    btnURL: '/'
    description: Désolé, mais la page que vous tentiez d'afficher n'existe pas.
  contact:
    labelFooter: SUIVEZ-NOUS
    enable: true
    topTitle: LAISSEZ-NOUS UN MESSAGE
    title: Contactez-Nous.
    subtitle: >-
      Des questions? Ou encore vous souhaitez discuter d'une nouvelle technologie avec laquelle nous pourrions vous aider?
      <br />
      <br />
      <b>Contactez-nous ou appelez-nous!</b>
    address: '3 Place Ville Marie, Montreal, QC H3B 2E3'
    addressLabel: Notre adresse
    phone: (514) 575-2497
    phoneLabel: Appelez-nous
    # fax: +61 3827 3590
    # facebook: 'https://www.facebook.com/'
    socialLabel: Suivez-Nous
    twitter: 'https://twitter.com/JDLabsMTL/'
    linkedin: 'https://www.linkedin.com/jdlabsmtl/'
    # dribbble: 'https://dribbble.com/'
    # instagram: 'https://www.instagram.com/'
    btnText: Envoyer
    mapLatitude: 45.501872
    mapLongitude: -73.568811
    mapMarker: images/marker.png
    namePlaceholder: Votre Nom
    messagePlaceholder: Message
    subjectPlaceholder: Sujet
    emailPlaceholder: Votre Courriel
    formActionURL: /api/index.php
    formActionSuccess: Merci de nous avoir contacté. Nous vous répondrons sous peu.
    formActionError: Nous sommes désolé une erreur c'est produite. Appelez-nous.

